collection/urls.py
from django.conf.urls import url

from .views import (
    collection_create,
    collection_detail,
    collection_update,
    collection_delete,
    link_add,
    search_link,
    home,
    about,
    link_delete,
)

urlpatterns = [
    # url(r'^$', collection_list, name='list'),
    url(r'^create$', collection_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/add$', link_add, name='add'),
    url(r'^(?P<slug>[\w-]+)(?:/(?P<tag>[\w-]+))?/$', collection_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/search$', search_link, name="search_link"),
    url(r'^(?P<slug>[\w-]+)/edit$', collection_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete$', collection_delete, name='delete'),
    url(r'^$', home, name='home'),
    url(r'^about$', about, name='about'),
    url(r'^link/(?P<id>\d+)/delete$', link_delete, name='link_delete' ),
    # url(r'^(?P<slug>[\w-]+)/delete$', collection_delete, name='collection_delete'),
]

share/urls.py
from django.conf import settings
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name="login"),
    url(r'^register/', register_view, name="register"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^', include("collection.urls", namespace="collection"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify

# Create your models here.


# class CollectionManager(models.Manager):
#     def active(self, *args, **kwargs):
#         return super(CollectionManager, self).filter(draft=False).filter(publish__lte=timezone.now())

class Collection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    privacy = models.NullBooleanField(default=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    # objects = CollectionManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("collection:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-update", "-id"]


class Tag(models.Model):
	name = models.CharField(max_length=120)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	class Meta:
		ordering = ["-timestamp"]


class Link(models.Model):
    title = models.CharField(max_length=120)
    link = models.TextField()
    domain = models.CharField(max_length=300)
    img = models.CharField(max_length=300)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
    	return self.title

    def __str__(self):
    	return self.title

    class Meta:
	   ordering = ["-timestamp"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs = Collection.objects.filter(slug=slug).order_by("-id")
    if qs.exists():
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug= new_slug)
    return slug


def pre_save_collection_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)

pre_save.connect(pre_save_collection_receiver, sender=Collection)

collection/forms.py
from django import forms
from .models import Collection, Link, Tag


class CollectionForm(forms.ModelForm):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Board Name'}))
    description = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-input',
     'placeholder': 'Small Descriptiono (Optional)', 'rows': 2, 'cols': 100}), required=False)
    privacy = forms.BooleanField(label='Make it a private board.', required=False)
    class Meta:
        model = Collection
        fields = [
            "title",
            "description",
            "privacy",
        ]


class LinkForm(forms.ModelForm):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Title (Optional)'}))
    link = forms.URLField(label="", widget=forms.TextInput(attrs={'placeholder': 'http://www.yourlink.com'}), required=True)
    tags = forms.ModelMultipleChoiceField(label="*Write custom tags and hit enter to attach", queryset=Tag.objects.all())
    class Meta:
        model = Link
        fields = [
            "title",
            "link",
            "tags",
        ]

collection/views.py
import os
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CollectionForm, LinkForm
from .models import Collection, Link, Tag
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from selenium import webdriver
from urlparse import urlparse
from PIL import Image
from django.views.decorators.csrf import csrf_exempt
import json
from django.core import serializers
from django.http import HttpResponseForbidden
# Create your views here.

@login_required
def collection_create(request):
    """
    Gets the post requset of storinig collection form, save it,
     and create a directory for saving images of it's links.

    @param:     post resuest
    @return     redirect to recent created collection page.

    """
    form = CollectionForm(request.POST)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # if not os.path.exists("./static/img/"+str(instance.id)+"/"):
        #     os.makedirs("./static/img/"+str(instance.id)+"/")
        return HttpResponseRedirect(instance.get_absolute_url())


def collection_detail(request, slug=None, tag=None):
    """
    """
    form_board = CollectionForm(None)
    form_link = LinkForm(None)
    query_list = Collection.objects.filter(slug=slug)
    if request.user.is_authenticated():
        query_list = Collection.objects.filter(user=request.user)
    if slug:
        collection = get_object_or_404(Collection, slug=slug)
    instance = Link.objects.filter(collection=collection)
    form_edit_board = CollectionForm(instance=collection)
    if collection.privacy==True and collection.user != request.user:
        response = HttpResponse("<h1 style='text-allign: center;'>Oops!! You do not have permissions.</h1>")
        response.status_code = 403
        return response

    tags = []
    for ins in instance:
        for x in ins.tags.all():
            if x not in tags:
                tags.append(x)
    if tag:
        instance = instance.filter(tags__name__icontains=tag)
    context = {
        "collection_list": query_list,
        "form_board": form_board,
        "form_edit_board": form_edit_board,
        "form_link": form_link,
        "instance": instance,
        "slug": collection.slug,
        "collection": collection,
        "tags": tags,
    }
    return render(request, "board.html", context)


def search_link(request, slug=None):
    if request.GET:
        collection = get_object_or_404(Collection, slug=slug)
        instance = Link.objects.filter(collection=collection)
        query = request.GET.get("q")
        instance = instance.filter(
            Q(title__icontains=query) |
            Q(tags__name__icontains=query) |
            Q(link__icontains=query)
        ).distinct()
        data = serializers.serialize('json', list(instance), fields=('link', 'title', 'domain', 'tags', 'img'))
        return HttpResponse(data, content_type="application/json")


@csrf_exempt
def link_add(request, slug=None):
    """
    Fetching Title and Screenshot(selenium webdriver, phantomjs) of the link & saving it,
    Cutting the domain name from the link string. Saving the title, link, img path, domain name in database,
    Fethcing img, compressing it and saving it back(PIL Image),
    Attaching the tags with link.

    @param request: Post request
    @param slug:    For getting the correnponding the collection(for foreign key field of Link model and 
                    creating a directory for the image by it's id)
    @return:    json response to the ajax request.

    """
    collection = get_object_or_404(Collection, slug=slug)
    if request.POST:
        link = request.POST.get('link')
        if not(link.startswith('http://') or link.startswith('https://')):
            link = 'http://'+link
        
        driver = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true','--ssl-protocol=any'])
        driver.set_window_position(0, 0)
        driver.set_window_size(1024, 720)
        driver.get(link)

        title = request.POST.get('title')
        if not title:
            title = driver.title.encode("utf-8")
        img_id = Link.objects.first()
        img_name = str(img_id.id + 1)
        img = img_name + ".png"
        domain = '{uri.netloc}'.format(uri=urlparse(link))
        if domain.startswith('www'):
            domain = domain[4:]
        
        instance = Link.objects.create(
            title=title,
            link=link,
            img= img,
            domain=domain,
            collection=collection,
        )
        driver.save_screenshot("/home/ubuntu/main/media_cdn/images/" + img_name + '.png')
        driver.quit();
        im = Image.open("/home/ubuntu/main/media_cdn/images/" + img_name + '.png')
        im = im.crop((0,0,1000,1000))
        im = im.resize((300, 300), Image.ANTIALIAS)
        im.save("/home/ubuntu/main/media_cdn/images/" + img_name + '.png')
        tags_response = []
        tags = request.POST.getlist('tags[]')
        for tag in tags:
            tag = tag.replace(" ", "_")
            try:
                tag = get_object_or_404(Tag, id=tag)
            except:
                pass
            x, created = Tag.objects.get_or_create(name = tag)
            tags_response.append(str(x))
            instance.tags.add(x)
        data = {
            'link': link,
            'title': title,
            'tags': tags_response,
            'image': img,
            'domain': domain,
            'id': instance.id,
            }
        return HttpResponse(json.dumps(data), content_type="application/json")


@login_required
@csrf_exempt
def collection_update(request, slug=None):
    instance = Collection.objects.get(slug=slug)
    if not (request.user.username == instance.user.username):
        response = HttpResponse("<h1>Sorry, this is not your board to edit.</h1>")
        response.status_code = 403
        return response
    instance.title = request.POST.get('title')
    instance.description = request.POST.get('description')
    instance.privacy = request.POST.get('privacy')
    instance.save()
    return HttpResponseRedirect(instance.get_absolute_url())


def home(request):
    if request.user.is_authenticated():
        form_board = CollectionForm(None)
        instance = Collection.objects.filter(user=request.user).first()
        if not instance:
            return render(request, 'create_board.html', {'form': form_board})
        return HttpResponseRedirect(instance.get_absolute_url())
    return render(request, 'home.html', {})


def about(request):
    return render(request, 'about.html', {})

@login_required
def collection_delete(request, slug=None):
    instance = Collection.objects.get(slug=slug)
    if not (request.user.username == instance.user.username):
        response = HttpResponse("<h1>Sorry, this is not your board to Delete.</h1>")
        response.status_code = 403
        return response
    links = Link.objects.filter(collection=instance)
    for link in links:
        if os.path.exists("/home/ubuntu/main/media_cdn/images/" + link.img):
            os.remove("/home/ubuntu/main/media_cdn/images/" + link.img)
    instance.delete()
    collection = Collection.objects.filter(user=request.user)
    if not collection:
        return render(request, 'create_board.html', {'form': form_board})
    link = collection.first().slug
    return redirect("/"+link+'/')


@login_required
def link_delete(request, id=None):
    instance = get_object_or_404(Link, id=id)
    collection = instance.collection
    if os.path.exists("/home/ubuntu/main/media_cdn/images/" + instance.img):
        os.remove("/home/ubuntu/main/media_cdn/images/" + instance.img)
    instance.delete()
    return HttpResponseRedirect(collection.get_absolute_url())

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Create Board Modal -->
<div class="modal fade" id="createBoard" tabindex="-1" role="dialog" aria-labelledby="createBoardLabel">
  <div class="modal-dialog add-link-dialog" role="document">
    <div class="modal-content add-link-content">
      <div class="modal-body">
        <h4 class="modal-title"> Create a new board </h4>
        <a class="close-modal" data-dismiss="modal" aria-label="Close">
    		<span aria-hidden="true"><i class="fa fa-times"></i></span>
    	</a>
      </div>
    </div>
  </div>
</div>

<!-- <nav class="navbar navbar-default navbar navbar-home navbar-fixed-top header topnav" role="navigation">
    <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
         </button>
        <a class="#" href="#"> <img src="{% static 'img/logo_w.png' %}" class="logo" alt="logo"></a>
     </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        	<div class="">
                <ul class="nav navbar-nav navbar-right">
 					<li> <a href="#" data-toggle="modal" data-target="#addLink"> How it works ? </a> </li>
 					<li> <a href="#" data-toggle="modal" data-target="#addLink"> Login </a> </li>
 					<li> <a href="#" data-toggle="modal" data-target="#addLink"> Sign up </a> </li>
                </ul>
             </div>
  	</div>
  	<div class="clearfix"></div>
</nav> -->
  <!-- Section Home -->
<section class="intro-header pos-rel">
    <div class="container">
    	<div class="bg-gradient"></div>
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
					<h1 class="text-bg text-center"> About Us </h1>
                    <h4 class="sec-title text-center"> We just love creating products which solve real life problems </h4>
                </div>
            </div>
        </div>
    </div>
</section>
  <section class="pad-75">
	<h1 class="text-center"> Our Team </h1>
	<div class="col-md-8 col-sm-10 col-xs-12 align-center">
		<div class="team-card col-md-6 col-sm-6 col-xs-12">
			<div class="img-container">
				<img src="{% static 'img/tohidur.png' %}" class="img-responsive" alt="Tohidur Rahaman Backend Developer">
			</div>
			<div class="info">
				<h3 class="name"> Tohidur Rahaman </h3>
				<h4 class="designation"> Backend Developer </h4>
			 	<p> Loves writing code and passionate about creating new products. </p>
			 	<div class="footer-links">
				 	<ul class="profile-links">
				 		<li><a href="https://linkedin.com/in/tohidur" target="_blank"> <i class="fa fa-linkedin"></i> </a> </li>
				 		<li><a href="https://angel.co/tohidur" target="_blank"> <i class="fa fa-angellist"></i> </a> </li>
				 		<li><a href="https://github.com/tohidur" target="_blank"> <i class="fa fa-github"></i> </a> </li>
				 		<li><a href="https://www.facebook.com/rh.tohidur" target="_blank"> <i class="fa fa-facebook"></i> </a> </li>
				 	</ul>
			 	</div>
			</div>
		</div>
		<div class="team-card col-md-6 col-sm-6 col-xs-12">
			<div class="img-container">
				<img src="{% static 'img/sushant.png' %}" class="img-responsive" alt="Sushant Kumar, Freelance Designer and Developer">
			</div>
			<div class="info">
				<h3 class="name"> Sushant Kumar </h3>
				<h4 class="designation"> Frontend Developer </h4>
			 	<p> Loves solving problems through business and technology </p>
			 	<div class="footer-links">
				 	<ul class="profile-links">
				 		<li><a href="https://linkedin.com/in/sushantkr" target="_blank"> <i class="fa fa-linkedin"></i> </a> </li>
				 		<li><a href="https://angel.co/sushantkr17" target="_blank"> <i class="fa fa-angellist"></i> </a> </li>
				 		<li><a href="https://github.com/sushantkr17" target="_blank"> <i class="fa fa-github"></i> </a> </li>
				 		<li><a href="https://www.facebook.com/Sushantkr17" target="_blank"> <i class="fa fa-facebook"></i> </a> </li>
				 		<li><a href="http://sushantkr.com" target="_blank"> <i class="fa fa-globe"></i> </a> </li>
				 	</ul>
			 	</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="clearfix"></div>
</section>
<footer class="get-started footer">
	<div class="container">
		<ul class="footer-links">
			<li class="left"> &copy; Putboard | 2016 </li>
			<li class="left"> <a href="/about"> About </a> </li>
			<li class="left"> <a href=""> Terms of Service </a> </li>
			<li class="left"> <a href=""> Privacy </a> </li>
			<li class="right"> <a href=""> <i class="fa fa-facebook"></i> </a> </li>
			<li class="right"> <a href=""> <i class="fa fa-twitter"></i> </a> </li>
			<li class="right"> <a href=""> <i class="fa fa-linkedin"></i> </a> </li>
		</ul>
	</div>
</footer>
{% endblock content %}

templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Collection of links from all over the world">
    <meta name="author" content="Putboard">
    <meta property="og:image" content="{%static 'img/desc1.png'%}"/>
    <!-- <meta name="twitter:image:src" content="https://www.dreamteamfc.com/c/s3/dreamteamfc-prod/uploads/2016/06/Lionel-Messi.jpg">
    <meta name="twitter:domain" content="YourDomain.com"> -->

    <title>Putboard</title>
    <link href="{% static "img/icons/favicon.ico"%}" rel="shortcut icon">
    <link href="{% static "css/bootstrap.min.css"%}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
    <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <style>
        .selectmultiple{
            width: 312px
        }
    </style>
    {% block style %}
    {%endblock%}
</head>
<body>
    <nav class="navbar navbar-default navbar navbar-home navbar-fixed-top header topnav" role="navigation">
        <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
             </button>
            <a class="" href="/"> <img src="{% static 'img/logo_w.png' %}" class="logo" alt="logo"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {% if not request.user.is_authenticated %}
            <div class="">
                <ul class="nav navbar-nav navbar-right">
                    <li> <a href="/login"> Login </a> </li>
                    <li class="btn-signup"> <a href="/register"> Sign up </a> </li>
                </ul>
            </div>
            {% else %}
            <div class="">
                <ul class="nav navbar-nav navbar-right">
                    <li class="user-profile">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="username">{{request.user.first_name}} <i class="fa fa-caret-down" aria-hidden="true"></i></spans>
                    </a>
                        <ul class="dropdown-menu more-actions">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            {% endif %}
        </div>
        <div class="clearfix"></div>
    </nav>
	{% block content %}
	{% endblock content %}
</body>
<script src="{% static "js/jquery.min.js" %}" ></script>
<script src="{% static "js/bootstrap.min.js" %}" ></script>
<script src="{% static "js/jquery.validate.min.js" %}" ></script>
<script src="{% static "js/select2.min.js"%}"></script>
<script type="text/javascript">
    $(function() {
        if($(window).width() < 460) {
            $("#site-wrapper").removeClass('show-nav');
        }
        // Toggle Nav on Click
        $('.toggle-nav').click(function() {
            // Calling a function in case you want to expand upon this.
            toggleNav();
        });
    });

    function toggleNav() {
        if ($('#site-wrapper').hasClass('show-nav')) {
            // Do things on Nav Close
            $('#site-wrapper').removeClass('show-nav');
            
        } else {
            // Do things on Nav Open
            $('#site-wrapper').addClass('show-nav');
           
        }

        //$('#site-wrapper').toggleClass('show-nav');
    }

    var slug = '{{slug}}';
    var wait = '{% static "img/icons/wait1.gif" %}';
    var favicon = '{% static "img/icons/favicon.ico" %}';
    var board_title = '{{collection.title}}';
    var board_description = '{{collection.description}}';
    var board_privacy = '{{collection.privacy}}'
    $('.selectmultiple').select2({
        placeholder: "Attach a Tag",
        dropdownAutoWidth: true,
        tags: true,
    });
</script>
<script src="{% static "js/home.js" %}" ></script>
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-69563118-3', 'auto');
 ga('send', 'pageview');

</script>
<!-- Hotjar Tracking Code for http://www.putboard.com -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:250600,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</html>

templates/collection_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
	{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}

	{% block content %}
    <br>
    <br>
    <form action="">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="search  by tags, links or title" name="q" value="{{ request.GET.q }}">
            <span class="input-group-btn">
            <input class="btn btn-default" type="submit" value="Search">
            </span>
        </div>
    </form>
    <div class="row">
    <br><br>
        <a href="add" class="btn btn-default">Add Link</a>
        <div class="col-sm-8 col-sm-offset-3">
        {% for obj in instance %}
            <div class="row">
                <div class="col-sm-2">
                    <h4>{{ obj.title }}</h4>
                </div>
                <div class="col-sm-4">
                    <a href="http://{{ obj.link }}" target="_blank"><h4>{{ obj.link }}</h4></a>
                </div>
                {% for ob in obj.tags.all %}
                    <p>{{ob}}</p>
                {%endfor%}
            </div>
            <br>
            <hr>
        {% endfor %}
        </div>
    </div>
	{% endblock content %}

templates/collection_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-sm-6">
        <h3>Create Collection</h3>
        <hr>
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <br>
        <input type="submit" class="btn btn-default btn-info" value="Create Post">
        </form>
        <br>
    </div>
{% endblock content %}

templates/collection_list.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-8 col-sm-offset-1">
    <h1>{{ title }}</h1>
    <form action="">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="search collections" name="q" value="{{ request.GET.q }}">
            <span class="input-group-btn">
            <input class="btn btn-default" type="submit" value="Search">
            </span>
        </div>
    </form>
    <br><br>
    </div>
    <div>
        <a href="/create" class="btn btn-default btn-danger ">Create New Collection</a>
    </div>
    <div style="margin-top: 120px">
    <div class="row">
        {% for obj in collection_list %}
            <div class="panel-body" style="float: left">
            <div class="col-sm-2 col-offset-1">
                <h3>{{ obj.title }}</a><br></h3>
                <p><a href='{{ obj.get_absolute_url }}' class="btn btn-primary" role="button">View</a></p>
            </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock content %}

templates/create_board.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{%block style%}
    <style>
        body{
            padding-top: 50px;
        }
    </style>
{% endblock %}
{% block content %}

<div class="main-container disp-table">
    <div class="user-login mar-t-50 align-center">
        <h2 class="form-title"> Create your first board </h2>
        <h4> </h4> 
        <form action="{% url 'collection:create' %}" id="formBoard" method="POST" class="login-form bg-white">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-lg btn-add-link btn-submit">
             Create Board
            </button>
        </form>

    </div>
</div>

{% endblock %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>{{ title }}</h1>
        <hr/>

        <form method="POST" action="">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-default" value="{{ title }}">
        </form>
    </div>
{% endblock content %}

templates/link_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-sm-6">
        <h3>Add Link</h3>
        <hr>
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-default btn-info" value="ADD">
        </form>
        <br>
    </div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block style%}
    <style>
        body{
            padding-top: 40px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="main-container disp-table">
        <div class="user-login mar-t-50 align-center">
            <h2 class="form-title"> Log in </h2>
            <form action="" method="POST" class="login-form bg-white">{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-lg btn-add-link btn-submit">
                 Log in
                </button>
                <label for="signup"> Not Registered yet ? <a href="/register"> Signup </a>
                <label> Forgot Password ? <a href="/resetpassword">Reset!</a></label>
            </form>

        </div>
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block style%}
    <style>
        body{
            padding-top: 40px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="main-container disp-table">
        <div class="user-login mar-t-50 align-center">
            <h2 class="form-title"> Sign up </h2>
            <form action="" method="POST" class="login-form bg-white">{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-lg btn-add-link btn-submit">
                 Sign Up
                </button>
                <label for="signup"> Already a user ? <a href="/login"> Login </a>
            </form>

        </div>
    </div>
{% endblock %}